# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile CXX with /usr/bin/c++
CXX_FLAGS =  -Wall -Wconversion -Wshadow -Wextra -pedantic -Werror=strict-aliasing -O3 -DNDEBUG   -std=c++11

CXX_DEFINES = 

CXX_INCLUDES = -I/home/long/code/jsoncpp/include -I/home/long/code/jsoncpp/src/lib_json/../../include 

